# -*- coding: utf-8 -*-
"""Advanced Looping Concepts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-ZvHt80ZfrNh6YDtE8GqO427MBGPBq5b
"""

# Advanced Looping Concepts
# syntax of list comprehension
# newlist = [ expression for item in iterable if condition]

numbers = [10, 20,30,40,50]
square = [ i**2 for i in numbers]
print(square)


num = [1,2,3,4,5,6,7,8]
even_no = [i%2 == 0 for i in num ]
print(even_no)

# using condition
n = [x for x in range(1,10) if x%2==0]
print(n)

# Nested List Comprehensions
result = [[j for j in range(11)] for i in range(11)]
print(result)

"""**Comprehensions provide a concise way to create lists, sets, and
dictionaries**

● List comprehension simplifies list creation using loops inside brackets.

● Set comprehension ensures unique values while following list
comprehension principles.


● Dictionary comprehension creates key-value pairs dynamically.

● Lambda functions provide a short syntax for defining functions without a
name.

● Using map() and filter() with lambda functions helps in efficient
transformations and filtering.

● Best practices include prioritizing readability and avoiding overuse of
complex comprehensions.



"""

from re import U
nums = {1,1,2,2,3,4,5,6,6,2}
new_set = [x for x in nums]
print(new_set)

#set comprehension
unique = { i for i in [10,10,20,30,404, 40,50,50]}
print(unique)

odd_no = {i for i in range(10) if i%2!= 0}
print(odd_no)

# # Dictionaries Comprehension
# new_dict = {key_expression: value_expression for item in iterable if condition}
n = [1,2,3,4,5,6,7]
sq = {x : x**2 for x in n}
print(sq)

even_dict = {x : x**2 for x in range(10) if x%2==0 }
print(even_dict)

nested_dict = { x:{y:y**2 for y in range(10)} for x in range(10) if x%2 ==0}

# lambda function - A lambda function is an anonymous function that can have multiple arguments but only one expression. syntax :- lambda arguments : expression
sq = lambda x : x**2
print(sq(4))

add = lambda x,y : x+y
print(add(5,5))

numbers = [1, 2, 3, 4]
squared_numbers = list(map(lambda x: x ** 2, numbers))
print(squared_numbers)

even_numbers = list(filter(lambda x: x % 2 == 0, range(10)))
print(even_numbers)
# Output: [0, 2, 4, 6, 8]