# -*- coding: utf-8 -*-
"""custom functions in python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16SdoW_5v378dHbcfBBZmqoT3XR0Fny_u
"""

def greet():
  print("hello , good morning")
greet()

def greet1(name): # using Parameters
  print("hello " + name + " Mam Good Morning")
greet1("Lovely")

#calling a function
def sum(x,y):
  print( "The sum is ", x+y)
sum(10,30)

# Positional Arguments - Arguments are passed in order when calling a function.
def full_name(first , last):
  print("my name is " + first + " " + last)
full_name("Monika" , "Saini")

# Keyword Arguments - Keyword arguments allow passing values using parameter names.
def gr(year , model):
  print(model , year)
gr(year = 2025, model = "BMW 320d")

#default Arguments - Default values are assigned to parameters if no value is provided.
def grt( name = "Lovely"):
  print("Hello " + name)
grt("Monika")
grt()

# Returning Values from a Function - sends back a value to the caller function
def square(num):
  return num*num
  # print(f'the sqaure of {num} is ', num*num)
square(5)

def calci(a,b):
  return a+b, a-b , a*b , a%b, a==b, a and b >0
result = calci(10,20)
print(result)

#infinite Recursion - Recursive functions must have a base condition to prevent infinite calls.
def infinite():
 print("This will never stop!")
 infinite()

def fact(num):
  if num ==0:
    return 1
  else:
    return num * fact(num-1)
print(fact(5))

# fnx to reverse a string
def reverse(name):
  print(name[::-1])
reverse("monika")

def find_max(num):
  return __builtins__.max(num)
print(find_max([10,20,5,90,45]))

def is_prime(num):
  if num<=1:
    return False

    for i in range(2, num):
      if num%i == 0:
        return False
  return True
number = 11
if is_prime(number):
    print(number, "is a prime number")
else:
    print(number, "is not a prime number")