# -*- coding: utf-8 -*-
"""Oops in Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rn3O1N9IcGcPSPToMkDsdnXn8yeUvLOs
"""

# A class is a blueprint for creating objects. It defines attributes (variables) and methods (functions) that objects can use.
class car:
  brand = "kia"
  model = "seltos"
print(car.brand)
print(car.model)


# using objects
class animal:
  def __init__(self,eat, sleep):
    self.eat = eat
    self.sleep = sleep
my_cat = animal("milk", "night")
my_deer = animal("grass", "morning")
print(my_cat.eat)
print(my_cat.sleep)
print(my_deer.sleep)

class cars:
  def __init__(self, brand , model):
    self.brand = brand
    self.model = model
car1 = cars("maruti", "baleno")
car2 = cars("hyundai", "creta")
print(car1.brand)
print(car1.model)
print(car2.model)
print(car2.brand)

class student:
  def __init__(self, name , age):
    self.name = name
    self.age = age
  def myfunc(self):
      print("hello my name is " + self.name)
stud = student("jessica", 22)
stud.myfunc()
stud.age= 30
print(stud.age)
print(stud.name)

# What are Methods?
# Methods are functions defined inside a class that operate on objects.

class student:
  def __init__(self, name , subject):
    self.name = name
    self.subject = subject
  def greet(self):
   return f'hello dear {self.name} , your subject is {self.subject}'
s1 = student("Monika", "Python")
print(s1.greet())
print(s1.name)
print(s1.subject)

# What is Polymorphism?
# Polymorphism allows different classes to share the same method name but with different implementations.

class dog:
  def speak(self):
    return "woof"
class cat:
  def speak(self):
    return "meow"
animals = [dog(), cat()]
for animal in animals:
  print(animal.speak())

class student:
  def read(self):
    return "reading"
class stud:
  def read(self):
    return "reading books"

students = [student(), stud()]
for student in students:
  print(student.read())

class Animal:
 def speak(self):
  return "Some sound"
class Dog(Animal):
 def speak(self):
  return "Woof!"
dog = Dog()
print(dog.speak())